
/*******************************************************************************
 * Copyright (c) 2012 Vojtisek.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Didier Vojtisek - initial API and implementation
 *******************************************************************************/
package fr.ffessm.doris.android.datamodel;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;

/** 
  *  
  */ 
@DatabaseTable(tableName = "photoFiche")
public class PhotoFiche {

	public static final String XML_PHOTOFICHE = "PHOTOFICHE";
	public static final String XML_ATT_ID = "id";
	public static final String XML_ATT_CLEURL = "cleURL";
	public static final String XML_ATT_IMAGEVIGNETTE = "imageVignette";
	public static final String XML_ATT_IMAGEMOYENNE = "imageMoyenne";
	public static final String XML_ATT_IMAGEGRANDE = "imageGrande";
	
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;
	

	@DatabaseField
	protected java.lang.String cleURL;

	protected java.io.File imageVignette;

	protected java.io.File imageMoyenne;

	protected java.io.File imageGrande;
	

	@DatabaseField(foreign = true) //, columnName = USER_ID_FIELD_NAME)
	protected Fiche fiche;

	// Start of user code PhotoFiche additional user properties
	// End of user code
	
	public PhotoFiche() {} // needed by ormlite
	public PhotoFiche(java.lang.String cleURL, java.io.File imageVignette, java.io.File imageMoyenne, java.io.File imageGrande) {
		super();
		this.cleURL = cleURL;
		this.imageVignette = imageVignette;
		this.imageMoyenne = imageMoyenne;
		this.imageGrande = imageGrande;
	} 

	public int getId() {
		return _id;
	}
	public void setId(int id) {
		this._id = id;
	}

	public java.lang.String getCleURL() {
		return this.cleURL;
	}
	public void setCleURL(java.lang.String cleURL) {
		this.cleURL = cleURL;
	}
	public java.io.File getImageVignette() {
		// Start of user code placeholder for derived attribute imageVignette
		// End of user code
		return this.imageVignette;
	}
	public void setImageVignette(java.io.File imageVignette) {
		this.imageVignette = imageVignette;
	}
	public java.io.File getImageMoyenne() {
		// Start of user code placeholder for derived attribute imageMoyenne
		// End of user code
		return this.imageMoyenne;
	}
	public void setImageMoyenne(java.io.File imageMoyenne) {
		this.imageMoyenne = imageMoyenne;
	}
	public java.io.File getImageGrande() {
		// Start of user code placeholder for derived attribute imageGrande
		// End of user code
		return this.imageGrande;
	}
	public void setImageGrande(java.io.File imageGrande) {
		this.imageGrande = imageGrande;
	}

	public String toXML(){
		StringBuilder sb = new StringBuilder();
		sb.append("<");
    	sb.append(XML_PHOTOFICHE);
		sb.append(" ");
    	sb.append(XML_ATT_ID);
    	sb.append("=\"");
		sb.append(this._id);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_CLEURL);
    	sb.append("=\"");
		sb.append(this.cleURL);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_IMAGEVIGNETTE);
    	sb.append("=\"");
		sb.append(this.imageVignette);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_IMAGEMOYENNE);
    	sb.append("=\"");
		sb.append(this.imageMoyenne);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_IMAGEGRANDE);
    	sb.append("=\"");
		sb.append(this.imageGrande);
    	sb.append("\" ");
    	sb.append(">");

		// TODO deal with other case

		sb.append("</");
    	sb.append(XML_PHOTOFICHE);
    	sb.append(">");
		return sb.toString();
	}
}
