/* *********************************************************************
 * Licence CeCILL-B
 * *********************************************************************
Copyright du Code : A COMPLÉTER  ([16/02/2013]) 

A COMPLÉTER : A COMPLÉTER@gmail.com

Ce logiciel est un programme informatique servant à afficher de manière 
ergonomique sur un terminal Android les fiches du site : doris.ffessm.fr. 

Les images, logos et textes restent la propriété de leurs auteurs, cf. : 
doris.ffessm.fr.

Ce logiciel est régi par la licence CeCILL-B soumise au droit français et
respectant les principes de diffusion des logiciels libres. Vous pouvez
utiliser, modifier et/ou redistribuer ce programme sous les conditions
de la licence CeCILL-B telle que diffusée par le CEA, le CNRS et l'INRIA 
sur le site "http://www.cecill.info".

En contrepartie de l'accessibilité au code source et des droits de copie,
de modification et de redistribution accordés par cette licence, il n'est
offert aux utilisateurs qu'une garantie limitée.  Pour les mêmes raisons,
seule une responsabilité restreinte pèse sur l'auteur du programme,  le
titulaire des droits patrimoniaux et les concédants successifs.

A cet égard  l'attention de l'utilisateur est attirée sur les risques
associés au chargement,  à l'utilisation,  à la modification et/ou au
développement et à la reproduction du logiciel par l'utilisateur étant 
donné sa spécificité de logiciel libre, qui peut le rendre complexe à 
manipuler et qui le réserve donc à des développeurs et des professionnels
avertis possédant  des  connaissances  informatiques approfondies.  Les
utilisateurs sont donc invités à charger  et  tester  l'adéquation  du
logiciel à leurs besoins dans des conditions permettant d'assurer la
sécurité de leurs systèmes et ou de leurs données et, plus généralement, 
à l'utiliser et l'exploiter dans les mêmes conditions de sécurité. 

Le fait que vous puissiez accéder à cet en-tête signifie que vous avez 
pris connaissance de la licence CeCILL-B, et que vous en avez accepté les
termes.
* Auteurs : Guillaume Mo <gmo7942@gmail.com>
*           Didier Vojtisek <dvojtise@gmail.com>
* ********************************************************************* */
package fr.ffessm.doris.android.datamodel;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;
import com.j256.ormlite.stmt.PreparedQuery;
import com.j256.ormlite.stmt.QueryBuilder;
import com.j256.ormlite.stmt.SelectArg;

import java.sql.SQLException;
import java.util.List;

import fr.ffessm.doris.android.datamodel.associations.*;

/** 
  *  
  */ 
@DatabaseTable(tableName = "photoParticipant")
public class PhotoParticipant {

	public static final String XML_PHOTOPARTICIPANT = "PHOTOPARTICIPANT";
	public static final String XML_ATT_ID = "id";
	public static final String XML_ATT_CLEURL = "cleURL";
	public static final String XML_ATT_IMAGE = "image";
	
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;
	

	@DatabaseField
	protected java.lang.String cleURL;

	protected java.io.File image;
	

	@DatabaseField(foreign = true) //, columnName = USER_ID_FIELD_NAME)
	protected Participant participant;

	// Start of user code PhotoParticipant additional user properties
	// End of user code
	
	public PhotoParticipant() {} // needed by ormlite
	public PhotoParticipant(java.lang.String cleURL, java.io.File image) {
		super();
		this.cleURL = cleURL;
		this.image = image;
	} 

	public int getId() {
		return _id;
	}
	public void setId(int id) {
		this._id = id;
	}

	public java.lang.String getCleURL() {
		return this.cleURL;
	}
	public void setCleURL(java.lang.String cleURL) {
		this.cleURL = cleURL;
	}
	public java.io.File getImage() {
		// Start of user code placeholder for derived attribute image
		// End of user code
		return this.image;
	}
	public void setImage(java.io.File image) {
		this.image = image;
	}

	public String toXML(){
		StringBuilder sb = new StringBuilder();
		sb.append("<");
    	sb.append(XML_PHOTOPARTICIPANT);
		sb.append(" ");
    	sb.append(XML_ATT_ID);
    	sb.append("=\"");
		sb.append(this._id);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_CLEURL);
    	sb.append("=\"");
		sb.append(this.cleURL);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_IMAGE);
    	sb.append("=\"");
		sb.append(this.image);
    	sb.append("\" ");
    	sb.append(">");

		// TODO deal with other case

		sb.append("</");
    	sb.append(XML_PHOTOPARTICIPANT);
    	sb.append(">");
		return sb.toString();
	}
}
