
/*******************************************************************************
 * Copyright (c) 2012 Vojtisek.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Didier Vojtisek - initial API and implementation
 *******************************************************************************/
package fr.ffessm.doris.android.datamodel;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;

/** 
  *  
  */ 
@DatabaseTable(tableName = "photoParticipant")
public class PhotoParticipant {

	public static final String XML_PHOTOPARTICIPANT = "PHOTOPARTICIPANT";
	public static final String XML_ATT_ID = "id";
	public static final String XML_ATT_CLEURL = "cleURL";
	public static final String XML_ATT_IMAGE = "image";
	
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;
	

	@DatabaseField
	protected java.lang.String cleURL;

	protected java.io.File image;
	

	// Start of user code PhotoParticipant additional user properties
	// End of user code
	
	public PhotoParticipant() {} // needed by ormlite
	public PhotoParticipant(java.lang.String cleURL, java.io.File image) {
		super();
		this.cleURL = cleURL;
		this.image = image;
	} 

	public int getId() {
		return _id;
	}
	public void setId(int id) {
		this._id = id;
	}

	public java.lang.String getCleURL() {
		return this.cleURL;
	}
	public void setCleURL(java.lang.String cleURL) {
		this.cleURL = cleURL;
	}
	public java.io.File getImage() {
		// Start of user code placeholder for derived attribute image
		// End of user code
		return this.image;
	}
	public void setImage(java.io.File image) {
		this.image = image;
	}

	public String toXML(){
		StringBuilder sb = new StringBuilder();
		sb.append("<");
    	sb.append(XML_PHOTOPARTICIPANT);
		sb.append(" ");
    	sb.append(XML_ATT_ID);
    	sb.append("=\"");
		sb.append(this._id);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_CLEURL);
    	sb.append("=\"");
		sb.append(this.cleURL);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_IMAGE);
    	sb.append("=\"");
		sb.append(this.image);
    	sb.append("\" ");
    	sb.append(">");

		// TODO deal with other case

		sb.append("</");
    	sb.append(XML_PHOTOPARTICIPANT);
    	sb.append(">");
		return sb.toString();
	}
}
