
/*******************************************************************************
 * Copyright (c) 2012 Vojtisek.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Didier Vojtisek - initial API and implementation
 *******************************************************************************/
package fr.ffessm.doris.android.datamodel;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;
import com.j256.ormlite.stmt.PreparedQuery;
import com.j256.ormlite.stmt.QueryBuilder;
import com.j256.ormlite.stmt.SelectArg;

import java.sql.SQLException;
import java.util.List;

import fr.ffessm.doris.android.datamodel.associations.*;

/** 
  *  
  */ 
@DatabaseTable(tableName = "sectionFiche")
public class SectionFiche {

	public static final String XML_SECTIONFICHE = "SECTIONFICHE";
	public static final String XML_ATT_ID = "id";
	public static final String XML_ATT_TITRE = "titre";
	public static final String XML_ATT_TEXTE = "texte";
	
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;
	

	@DatabaseField
	protected java.lang.String titre;

	@DatabaseField
	protected java.lang.String texte;
	

	@DatabaseField(foreign = true) //, columnName = USER_ID_FIELD_NAME)
	protected Fiche fiche;

	// Start of user code SectionFiche additional user properties
	// End of user code
	
	public SectionFiche() {} // needed by ormlite
	public SectionFiche(java.lang.String titre, java.lang.String texte) {
		super();
		this.titre = titre;
		this.texte = texte;
	} 

	public int getId() {
		return _id;
	}
	public void setId(int id) {
		this._id = id;
	}

	public java.lang.String getTitre() {
		return this.titre;
	}
	public void setTitre(java.lang.String titre) {
		this.titre = titre;
	}
	public java.lang.String getTexte() {
		return this.texte;
	}
	public void setTexte(java.lang.String texte) {
		this.texte = texte;
	}

	public String toXML(){
		StringBuilder sb = new StringBuilder();
		sb.append("<");
    	sb.append(XML_SECTIONFICHE);
		sb.append(" ");
    	sb.append(XML_ATT_ID);
    	sb.append("=\"");
		sb.append(this._id);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_TITRE);
    	sb.append("=\"");
		sb.append(this.titre);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_TEXTE);
    	sb.append("=\"");
		sb.append(this.texte);
    	sb.append("\" ");
    	sb.append(">");

		// TODO deal with other case

		sb.append("</");
    	sb.append(XML_SECTIONFICHE);
    	sb.append(">");
		return sb.toString();
	}
}
