
/*******************************************************************************
 * Copyright (c) 2012 Vojtisek.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Didier Vojtisek - initial API and implementation
 *******************************************************************************/
package fr.ffessm.doris.android.datamodel;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "photoFiche")
public class PhotoFiche {

	public static final String XML_PHOTOFICHE = "PHOTOFICHE";
	public static final String XML_ATT_ID = "id";
	
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;
	
	
	// Start of user code PhotoFiche additional properties
	// End of user code
	
	public PhotoFiche() {}// needed by ormlite
	public PhotoFiche() {
		super();
	} 

	public int getId() {
		return _id;
	}
	public void setId(int id) {
		this._id = id;
	}


	public String toXML(){
		StringBuilder sb = new StringBuilder();
		sb.append("<");
    	sb.append(XML_PHOTOFICHE);
		sb.append(" ");
    	sb.append(XML_ATT_ID);
    	sb.append("=\"");
		sb.append(this._id);
    	sb.append("\" ");
    	sb.append(">");

		// TODO deal with other case

		sb.append("</");
    	sb.append(XML_PHOTOFICHE);
    	sb.append(">");
		return sb.toString();
	}
}
