# 

image: openjdk:11-jdk

variables:

  # ANDROID_COMPILE_SDK is the version of Android you're compiling with.
  # It should match compileSdkVersion.
  ANDROID_COMPILE_SDK: "31"

  # ANDROID_BUILD_TOOLS is the version of the Android build tools you are using.
  # It should match buildToolsVersion.
  ANDROID_BUILD_TOOLS: "30.0.2"

  # It's what version of the command line tools we're going to download from the official site.
  # Official Site-> https://developer.android.com/studio/index.html
  # There, look down below at the cli tools only, sdk tools package is of format:
  #        commandlinetools-os_type-ANDROID_SDK_TOOLS_latest.zip
  # when the script was last modified for latest compileSdkVersion, it was which is written down below
  ANDROID_SDK_TOOLS: "8092744"

cache:
  - key: android-home
    paths:
      - android-home
  - key: gradle-cache-key
    paths:
      - .gradle
  - key: "doris_db"
    paths:
      - DorisAndroidPrefetch/run


stages:          # List of stages for jobs, and their order of execution
  - prepare_data
  - build

# Packages installation before running script
#before_script:
# Define some reusable functions
.install-android-sdk: &install-android-sdk
  # TODO transform into a docker image instead of download on every build
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1

  # Setup path as android_home for moving/exporting the downloaded sdk into it
  - export ANDROID_HOME="${PWD}/android-home"
  # Create a new directory at specified location
  - install -d $ANDROID_HOME
  # Here we are installing androidSDK tools from official source,
  # (the key thing here is the url from where you are downloading these sdk tool for command line, so please do note this url pattern there and here as well)
  # after that unzipping those tools and
  # then running a series of SDK manager commands to install necessary android SDK packages that'll allow the app to build
  - |
    if [[ ! -d $ANDROID_HOME/cmdline-tools/${ANDROID_SDK_TOOLS} ]]
    then
      wget --output-document=$ANDROID_HOME/cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip
      # move to the archive at ANDROID_HOME
      pushd $ANDROID_HOME
      unzip -d cmdline-tools cmdline-tools.zip
      mv cmdline-tools/cmdline-tools cmdline-tools/$ANDROID_SDK_TOOLS
      ln -s ${ANDROID_HOME}/cmdline-tools/$ANDROID_SDK_TOOLS ${ANDROID_HOME}/cmdline-tools/latest
      popd
    else
      echo "commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest already installed"
    fi
  - export PATH=$PATH:${ANDROID_HOME}/cmdline-tools/latest/bin/

  # Nothing fancy here, just checking sdkManager version
  - sdkmanager --version

  # use yes to accept all licenses
  - yes | sdkmanager --sdk_root=${ANDROID_HOME} --licenses || true
  - sdkmanager --sdk_root=${ANDROID_HOME} "platforms;android-${ANDROID_COMPILE_SDK}"
  - sdkmanager --sdk_root=${ANDROID_HOME} "platform-tools"
  - sdkmanager --sdk_root=${ANDROID_HOME} "build-tools;${ANDROID_BUILD_TOOLS}"

  # Not necessary, but just for surity
  - chmod +x ./gradlew

.create_sign_info: &create-sign-info
  - pwd
  - mkdir -p /builds/keystore
  - echo "$DORISANDROID_KEYSTORE" | base64 -d > /builds/keystore/doris_android.keystore
  - echo "keyAlias=doris" > /builds/keystore/sign.properties
  - echo "storePassword=$KEYSTORE_PASSWORD" >>  /builds/keystore/sign.properties
  - echo "storeFile=/builds/keystore/doris_android.keystore" >> /builds/keystore/sign.properties
  - echo "keyPassword=$KEY_PASSWORD" >> /builds/keystore/sign.properties


.show_cache_content: &show_cache_content
  - set +e
  - pwd
  - ls -lsa DorisAndroidPrefetch/run
  - ls -lsa DorisAndroidPrefetch/run/database
  - ls -lsa .gradle
  - set -e

collect-db-job:
  stage: prepare_data
  resource_group: doris_web_site
  before_script:
    - *show_cache_content
    - cat /builds/keystore/sign.properties || true
  script:
    - echo "Get DB from doris web site"
    - ./gradlew buildDorisDBV4_limited
  after_script:
    - *show_cache_content
  allow_failure: true
  artifacts:
    when: always
    paths:
      - DorisAndroidPrefetch/run/

build-job:
  stage: build
  before_script:
    - *show_cache_content
    - *install-android-sdk
    - *create-sign-info
  script:
    - cp DorisAndroidPrefetch/run/database DorisAndroid/src/main/asset
    - ./gradlew clean build lint
  after_script:
    - *show_cache_content
  artifacts:
    paths:
      - DorisAndroid/build/outputs/apk/**/*.apk
      - DorisAndroid/build/reports/
    #reports:
    #  junit: DorisAndroid/build/reports/*.xml

