
/*******************************************************************************
 * Copyright (c) 2012 Vojtisek.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Didier Vojtisek - initial API and implementation
 *******************************************************************************/
package fr.ffessm.doris.android.datamodel;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "card")
public class Card {

	public static final String XML_CARD = "CARD";
	public static final String XML_ATT_ID = "id";
	public static final String XML_ATT_SCIENTIFICNAME = "scientificName";
	public static final String XML_ATT_IDDORIS = "idDoris";
	
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected long _id;
	
	@DatabaseField
	protected java.lang.String scientificName;
	@DatabaseField
	protected int idDoris;
	
	//@DatabaseField(foreign = true, columnName = USER_ID_FIELD_NAME)
	//protected Participant writer;
	//@DatabaseField(foreign = true, columnName = USER_ID_FIELD_NAME)
	//protected Participant verifier;
	@ForeignCollectionField(eager = false)
	protected ForeignCollection<Picture> pictures;
	// Start of user code Card additional properties
	// End of user code
	
	public Card() {}// needed by ormlite
	public Card(java.lang.String scientificName, int idDoris) {
		super();
		this.scientificName = scientificName;
		this.idDoris = idDoris;
	} 

	public long getId() {
		return _id;
	}
	public void setId(long id) {
		this._id = id;
	}

	public java.lang.String getScientificName() {
		return this.scientificName;
	}
	public void setScientificName(java.lang.String scientificName) {
		this.scientificName = scientificName;
	}
	public int getIdDoris() {
		return this.idDoris;
	}
	public void setIdDoris(int idDoris) {
		this.idDoris = idDoris;
	}

	public String toXML(){
		StringBuilder sb = new StringBuilder();
		sb.append("<");
    	sb.append(XML_CARD);
		sb.append(" ");
    	sb.append(XML_ATT_ID);
    	sb.append("=\"");
		sb.append(this._id);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_SCIENTIFICNAME);
    	sb.append("=\"");
		sb.append(this.scientificName);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_IDDORIS);
    	sb.append("=\"");
		sb.append(this.idDoris);
    	sb.append("\" ");
    	sb.append(">");

		// TODO deal with other case

		sb.append("</");
    	sb.append(XML_CARD);
    	sb.append(">");
		return sb.toString();
	}
}
