
/*******************************************************************************
 * Copyright (c) 2012 Vojtisek.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Didier Vojtisek - initial API and implementation
 *******************************************************************************/
package fr.ffessm.doris.android.datamodel;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "picture")
public class Picture {

	public static final String XML_PICTURE = "PICTURE";
	public static final String XML_ATT_ID = "id";
	public static final String XML_ATT_NAME = "name";
	
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected long _id;
	
	@DatabaseField
	protected java.lang.String name;
	
	//@DatabaseField(foreign = true, columnName = USER_ID_FIELD_NAME)
	//protected Participant author;
	// Start of user code Picture additional properties
	// End of user code
	
	public Picture() {}// needed by ormlite
	public Picture(java.lang.String name) {
		super();
		this.name = name;
	} 

	public long getId() {
		return _id;
	}
	public void setId(long id) {
		this._id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}
	public void setName(java.lang.String name) {
		this.name = name;
	}

	public String toXML(){
		StringBuilder sb = new StringBuilder();
		sb.append("<");
    	sb.append(XML_PICTURE);
		sb.append(" ");
    	sb.append(XML_ATT_ID);
    	sb.append("=\"");
		sb.append(this._id);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_NAME);
    	sb.append("=\"");
		sb.append(this.name);
    	sb.append("\" ");
    	sb.append(">");

		// TODO deal with other case

		sb.append("</");
    	sb.append(XML_PICTURE);
    	sb.append(">");
		return sb.toString();
	}
}
