
/*******************************************************************************
 * Copyright (c) 2012 Vojtisek.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Didier Vojtisek - initial API and implementation
 *******************************************************************************/
package fr.ffessm.doris.android.datamodel;

import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "participantPhoto")
public class ParticipantPhoto {

	public static final String XML_PARTICIPANTPHOTO = "PARTICIPANTPHOTO";
	public static final String XML_ATT_ID = "id";
	public static final String XML_ATT_PHOTOFILENAME = "photoFileName";
	
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;
	
	@DatabaseField
	protected java.lang.String photoFileName;
	
	// Start of user code ParticipantPhoto additional properties
	// End of user code
	
	public ParticipantPhoto() {}// needed by ormlite
	public ParticipantPhoto(java.lang.String photoFileName) {
		super();
		this.photoFileName = photoFileName;
	} 

	public int getId() {
		return _id;
	}
	public void setId(int id) {
		this._id = id;
	}

	public java.lang.String getPhotoFileName() {
		return this.photoFileName;
	}
	public void setPhotoFileName(java.lang.String photoFileName) {
		this.photoFileName = photoFileName;
	}

	public String toXML(){
		StringBuilder sb = new StringBuilder();
		sb.append("<");
    	sb.append(XML_PARTICIPANTPHOTO);
		sb.append(" ");
    	sb.append(XML_ATT_ID);
    	sb.append("=\"");
		sb.append(this._id);
    	sb.append("\" ");
		sb.append(" ");
    	sb.append(XML_ATT_PHOTOFILENAME);
    	sb.append("=\"");
		sb.append(this.photoFileName);
    	sb.append("\" ");
    	sb.append(">");

		// TODO deal with other case

		sb.append("</");
    	sb.append(XML_PARTICIPANTPHOTO);
    	sb.append(">");
		return sb.toString();
	}
}
