package fr.vojtisek.adm.data.db;

import java.util.Date;


import com.j256.ormlite.dao.ForeignCollection;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.field.ForeignCollectionField;
import com.j256.ormlite.table.DatabaseTable;

@DatabaseTable(tableName = "diveEntries")
public class DiveEntry {
	
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	int id;
	
	@DatabaseField
	private Date date;
	
	@DatabaseField
	private String location;
	
	@DatabaseField
	private Integer maxdepth;
	
	@DatabaseField
	private Integer duration;
	
	@DatabaseField
	private Integer airtemperature;
	
	@DatabaseField
    private Integer altitude;
	
	@ForeignCollectionField(eager = false)
	ForeignCollection<DiveBudy> budies;
	
	@ForeignCollectionField(eager = false)
	ForeignCollection<DiveSite> sites;
	
	@ForeignCollectionField(eager = false)
	ForeignCollection<DiveStructure> structures;
	
    //private String density;
    //private String divenumber;
    //private UddfFileEquipmentUsed equipmentused;
    
    @DatabaseField
    private Integer lowesttemperature;
	
	
	
	public DiveEntry(){}; // needed by ormlite
	
	public DiveEntry(Date date, String location, Integer maxdepth,
			Integer duration) {
		super();
		//this.setId(id);
		this.date = date;
		this.location = location;
		this.maxdepth = maxdepth;
		this.duration = duration;
	}
	public Date getDate() {
		return date;
	}
	public void setDate(Date date) {
		this.date = date;
	}
	public String getLocation() {
		return location;
	}
	public void setLocation(String location) {
		this.location = location;
	}
	public Integer getMaxdepth() {
		return maxdepth;
	}
	public void setMaxdepth(Integer maxdepth) {
		this.maxdepth = maxdepth;
	}
	public Integer getDuration() {
		return duration;
	}
	public void setDuration(Integer duration) {
		this.duration = duration;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	

	
}
