/*
 * Project: JDiveLog: A Dive Logbook written in Java
 * File: DiveSite.java
 * 
 * @author Pascal Pellmont <jdivelog@pellmont.dyndns.org>
 * 
 * This file is part of JDiveLog.
 * JDiveLog is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.

 * JDiveLog is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with JDiveLog; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
package fr.vojtisek.adm.data.db;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;



@DatabaseTable(tableName = "diveSites")
public class DiveSite /*implements Comparable<DiveSite>*/ {
	
	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
    private String id;
    
    
   /* private String publicId;
    private boolean publish;
    private boolean published;
    private String ownerId; */
    private String spot;
    private String city;
    private String state;
    private String country;
     // private String waters;
    //private String timezone;
    private String description;
    private String directions;
    private String warnings;
    private String privateRemarks;
    //private int siteType;
    private String longitude;
    private String latitude;
    private Integer maxDepth;
    private Integer avgDepth;
    private Integer minDepth;
    private Integer altitude;
    //private String mainDiveActivity;
    //private String evaluation;
    
    public DiveSite(){}; // needed by ormlite

}
