
/*******************************************************************************
 * Copyright (c) 2012 Vojtisek.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Didier Vojtisek - initial API and implementation
 *******************************************************************************/
package fr.ffessm.doris.android.datamodel.associations;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import fr.ffessm.doris.android.datamodel.*;

/** 
  *  
  */ 
@DatabaseTable(tableName = "fiche_Photos")
public class Fiche_Photos {

 
	
	public final static String PHOTOFICHE_ID_FIELD_NAME = "PhotoFiche_id";
	public final static String FICHE_ID_FIELD_NAME = "Fiche_id";

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;
	
	// This is a foreign object which just stores the id from the User object in this table.
	@DatabaseField(foreign = true, columnName = PHOTOFICHE_ID_FIELD_NAME)
	PhotoFiche photoFiche;

	// This is a foreign object which just stores the id from the Post object in this table.
	@DatabaseField(foreign = true, columnName = FICHE_ID_FIELD_NAME)
	Fiche fiche;

	Fiche_Photos() {
		// for ormlite
	}

	public Fiche_Photos(PhotoFiche photoFiche, Fiche fiche) {
		this.photoFiche = photoFiche;
		this.fiche = fiche;
	}
}
