
/*******************************************************************************
 * Copyright (c) 2012 Vojtisek.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Didier Vojtisek - initial API and implementation
 *******************************************************************************/
package fr.ffessm.doris.android.datamodel.associations;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import fr.ffessm.doris.android.datamodel.*;

/** 
  *  
  */ 
@DatabaseTable(tableName = "fiches_ZonesObservations")
public class Fiches_ZonesObservations {

 
	
	public final static String FICHE_ID_FIELD_NAME = "Fiche_id";
	public final static String ZONEOBSERVATION_ID_FIELD_NAME = "ZoneObservation_id";

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;
	
	// This is a foreign object which just stores the id from the User object in this table.
	@DatabaseField(foreign = true, columnName = FICHE_ID_FIELD_NAME)
	Fiche fiche;

	// This is a foreign object which just stores the id from the Post object in this table.
	@DatabaseField(foreign = true, columnName = ZONEOBSERVATION_ID_FIELD_NAME)
	ZoneObservation zoneObservation;

	Fiches_ZonesObservations() {
		// for ormlite
	}

	public Fiches_ZonesObservations(Fiche fiche, ZoneObservation zoneObservation) {
		this.fiche = fiche;
		this.zoneObservation = zoneObservation;
	}
}
