
/*******************************************************************************
 * Copyright (c) 2012 Vojtisek.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Didier Vojtisek - initial API and implementation
 *******************************************************************************/
package fr.ffessm.doris.android.datamodel.associations;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

import fr.ffessm.doris.android.datamodel.*;

/** 
  *  
  */ 
@DatabaseTable(tableName = "participant_Photos")
public class Participant_Photos {

 
	
	public final static String PARTICIPANT_ID_FIELD_NAME = "Participant_id";
	public final static String PHOTOPARTICIPANT_ID_FIELD_NAME = "PhotoParticipant_id";

	// id is generated by the database and set on the object automagically
	@DatabaseField(generatedId = true)
	protected int _id;
	
	// This is a foreign object which just stores the id from the User object in this table.
	@DatabaseField(foreign = true, columnName = PARTICIPANT_ID_FIELD_NAME)
	Participant participant;

	// This is a foreign object which just stores the id from the Post object in this table.
	@DatabaseField(foreign = true, columnName = PHOTOPARTICIPANT_ID_FIELD_NAME)
	PhotoParticipant photoParticipant;

	Participant_Photos() {
		// for ormlite
	}

	public Participant_Photos(Participant participant, PhotoParticipant photoParticipant) {
		this.participant = participant;
		this.photoParticipant = photoParticipant;
	}
}
