name: cleanup all DorisDB caches
on: workflow_dispatch

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write # Grants permission to write to GitHub Actions (includes deleting caches)
    steps:
      - name: Cleanup
        run: |
          gh extension install actions/gh-actions-cache

          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R $REPO -L 100 | grep dorisdb-cache | cut -f 1 )

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
              echo "Attempting to delete cache: $cacheKey"
              gh actions-cache delete "$cacheKey" -R "${REPO}" --confirm
              if [ $? -eq 0 ]; then
                  echo "Successfully deleted cache: $cacheKey"
              else
                  echo "Failed to delete cache (or it was already deleted): $cacheKey"
              fi
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}