name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release-apk:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - PrefetchDB.collect-db-job # This job depends on the 'collect-db-job' job in the 'PrefetchDB.yml' file.
      - BuildAndroid.build-android-app-job # This job depends on the 'build-android-app-job' job in the 'BuildAndroid.yml' file.
    steps:
      - name: Get DorisDB (from previous jobs)
        uses: actions/download-artifact@v3
        with:
          name: doris-db-artifacts
          path: DorisAndroidPrefetch/run
      - name: Get DorisAndroid apk (from previous jobs)
        uses: actions/download-artifact@v3
        with:
          name: doris-db-artifacts
          path: DorisAndroidPrefetch/run
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "DorisAndroidPrefetch/run/database/DorisAndroid.db,DorisAndroid/build/outputs/apk/**/*.apk"
          artifactErrorsFailBuild: true
          # bodyFile: "body.md"