package fr.ffessm.doris.android.datamodel;

import com.j256.ormlite.field.DatabaseField;


/**
 * Generic class for all objects coming from the DB
 */
public class AbstractWebNodeObject {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    protected int _id;

    /** last modification date */
    @DatabaseField
    protected int modificationDate;

    /** node id  in the web API */
    @DatabaseField
    protected int webNodeId;

    public int getId() {
        return _id;
    }
    public void setId(int id) {
        this._id = id;
    }

    public int getModificationDate() {
        return this.modificationDate;
    }
    public void setModificationDate(int modificationDate) {
        this.modificationDate = modificationDate;
    }

    public int getWebNodeId() {
        return webNodeId;
    }

    public void setWebNodeId(int webNodeId) {
        this.webNodeId = webNodeId;
    }
}
